package com.bank.bian.informationprovideroperation;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Information Provider Operation
 *
 * Business Area:      Reference Data
 * Business Domain:    Reference Data
 * Functional Pattern: Operate
 * Asset Type:         Information Feed
 * Control Record:     Information Feed Operating Session
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Information Provider Operation — BIAN Semantic API")
                .description("Service Domain 'Information Provider Operation' (Operate pattern) "
                        + "operating on the 'Information Feed Operating Session' control record.")
                .version("0.1.0"));
    }
}
